### ISSUE TITLE
Has anyone ever tested this template?

### ISSUE THREAD

**Issue by NekoAria** [RSSerpent/template#6]
I was following the document, and this is what happened:
```Shell
$ git commit -m "initial commit"

Nitpick Check............................................................Failed
- hook id: nitpick-check
- exit code: 1

/root/.pre-commit-config.yaml:1: NIP103  should exist: Create the file with the contents below, then run 'pre-commit install'
/root/pyproject.toml:1: NIP103  should exist: Install poetry and run 'poetry init' to create it
/root/.editorconfig:1: NIP321  was not found. Create it with this content:
root = True

[*]
end_of_line = lf
indent_size = 4
indent_style = space
insert_final_newline = True
trim_trailing_whitespace = True

[*.py]
charset = utf-8

[*.{js,json}]
charset = utf-8
indent_size = 2

[*.{yml,yaml,md,rb}]
indent_size = 2

[Makefile]
indent_style = tab
/root/.pre-commit-config.yaml:1: NIP331  was not found. Create it with this content:
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    hooks:
      - id: pyupgrade
  - repo: https://github.com/openstack/bashate
    rev: 2.0.0
    hooks:
      - id: bashate
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/psf/black
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.5b2]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions,
          flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill, flake8-pytest,
          flake8-quotes, flake8-typing-imports, yesqa]
  - repo: https://github.com/PyCQA/isort
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
/root/.pylintrc:1: NIP321  was not found. Create it with this content:
[BASIC]
bad-functions = map,filter
good-names = i,j,k,e,ex,Run,_,id,rv

[FORMAT]
indent-after-paren = 4
max-line-length = 120
max-module-lines = 1000

[MASTER]
jobs = 1

[REPORTS]
output-format = colorized

[SIMILARITIES]
ignore-comments = yes
ignore-docstrings = yes
ignore-imports = no
min-similarity-lines = 4

[VARIABLES]
dummy-variables-rgx = _$|dummy
/root/package.json:1: NIP348  has missing keys:
{
  "name": "<some value here>",
  "release": {
    "plugins": "<some value here>"
  },
  "repository": {
    "type": "<some value here>",
    "url": "<some value here>"
  },
  "version": "<some value here>"
}
/root/package.json:1: NIP348  has missing values:
{
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  }
}
/root/pyproject.toml:1: NIP311  was not found. Create it with this content:
[tool.black]
line-length = 120

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.extras]
lint = [ "pylint",]

[tool.poetry.dependencies.pylint]
optional = true
version = "*"
/root/setup.cfg:1: NIP321  was not found. Create it with this content:
[flake8]
exclude = .tox,build
ignore = D107,D202,D203,D401,E203,E402,E501,W503
inline-quotes = double
max-line-length = 120

[isort]
combine_as_imports = True
force_grid_wrap = 0
include_trailing_comma = True
known_first_party = tests
line_length = 120
multi_line_output = 3
skip = .tox,build

[mypy]
follow_imports = skip
ignore_missing_imports = True
strict_optional = True
warn_no_return = True
warn_redundant_casts = True
warn_unused_ignores = True
/root/tox.ini:1: NIP321  was not found. Create it with this content:
[coverage:report]
precision = 2
show_missing = True
skip_covered = True
skip_empty = True
sort = Cover

[coverage:run]
branch = True
parallel = True
relative_files = True
source = src/

[testenv]
description = Run tests with pytest and coverage
extras = test

[tox]
isolated_build = True
Violations: ❌ 10 to change manually.
```

**Comment by NekoAria** [comment]
And then, I followed the error info:
```Shell
Nitpick Check............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check Blanket "#noqa"....................................................Passed
Check Blanket "#type:ignore".............................................Passed
Upgrade Python Syntax....................................................Passed
Check Typos..............................................................Passed
Format Source Code.......................................................Passed
Sort Imports.............................................................Passed
Type Check...............................................................Passed
Lint.....................................................................Passed
[INFO] Installing environment for https://github.com/commitizen-tools/commitizen.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check Commit Message.....................................................Failed
- hook id: commitizen
- exit code: 14

commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "initial commit"
pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)
```

**Comment by haukeng** [comment]
> And then, I followed the error info:
> 
> ```shell
> Nitpick Check............................................................Passed
> Fix End of Files.........................................................Passed
> Trim Trailing Whitespace.................................................Passed
> Check Blanket "#noqa"....................................................Passed
> Check Blanket "#type:ignore".............................................Passed
> Upgrade Python Syntax....................................................Passed
> Check Typos..............................................................Passed
> Format Source Code.......................................................Passed
> Sort Imports.............................................................Passed
> Type Check...............................................................Passed
> Lint.....................................................................Passed
> [INFO] Installing environment for https://github.com/commitizen-tools/commitizen.
> [INFO] Once installed this environment will be reused.
> [INFO] This may take a few minutes...
> Check Commit Message.....................................................Failed
> - hook id: commitizen
> - exit code: 14
> 
> commit validation: failed!
> please enter a commit message in the commitizen format.
> commit "": "initial commit"
> pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)
> ```

Your commit message did not pass the commitizen check.

The commit message should match the following regular expression.

`(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)`

**Comment by NekoAria** [comment]
> > And then, I followed the error info:
> > ```shell
> > Nitpick Check............................................................Passed
> > Fix End of Files.........................................................Passed
> > Trim Trailing Whitespace.................................................Passed
> > Check Blanket "#noqa"....................................................Passed
> > Check Blanket "#type:ignore".............................................Passed
> > Upgrade Python Syntax....................................................Passed
> > Check Typos..............................................................Passed
> > Format Source Code.......................................................Passed
> > Sort Imports.............................................................Passed
> > Type Check...............................................................Passed
> > Lint.....................................................................Passed
> > [INFO] Installing environment for https://github.com/commitizen-tools/commitizen.
> > [INFO] Once installed this environment will be reused.
> > [INFO] This may take a few minutes...
> > Check Commit Message.....................................................Failed
> > - hook id: commitizen
> > - exit code: 14
> > 
> > commit validation: failed!
> > please enter a commit message in the commitizen format.
> > commit "": "initial commit"
> > pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)
> > ```
> 
> Your commit message did not pass the commitizen check.
> 
> The commit message should match the following regular expression.
> 
> `(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)`

I know, but why do I have to do all this extra work?
I mean those files and the commit message prefix.
And which prefix do you think is most appropriate?

**Comment by queensferryme** [comment]
Hi @NekoAria, I'm sorry for the inconvenience. I suppose you've read this [document](https://docs.rsserpent.com/contribution/plugin/) right? I try to run `cookiecutter gh:rsserpent/template` creating a new plugin from scratch and could not reproduce your first error. Could you give more details to help me reproduce?

As for the second error, I am looking for some way to configure the `commitizen` hook to accept some common commit messages like `initial commit` & `Merge...`.

RSSerpent is still at its early stages and a lot of things might be buggy. Again I am sorry for your inconvenience and thanks for your feedback!

**Comment by NekoAria** [comment]
> Hi @NekoAria, I'm sorry for the inconvenience. I suppose you've read this [document](https://docs.rsserpent.com/contribution/plugin/) right? I try to run `cookiecutter gh:rsserpent/template` creating a new plugin from scratch and could not reproduce your first error. Could you give more details to help me reproduce?
> 
> As for the second error, I am looking for some way to configure the `commitizen` hook to accept some common commit messages like `initial commit` & `Merge...`.
> 
> RSSerpent is still at its early stages and a lot of things might be buggy. Again I am sorry for your inconvenience and thanks for your feedback!

Yes, I just followed the document.

After reading your reply, it occurred to me that maybe there was something wrong with my system environment.
Just now, I switched to another Linux server to test, and it didn’t reproduce the first case.

I'm sorry I was in a bad mood.
